POST http://localhost:8080/post
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNob2toMUBleGFtcGxlLmNvbSIsImV4cCI6MTc2MDUxNzIyMSwidXNlcm5hbWUiOiJzaG9raDEifQ.ovLzIu88hoZPnWUrdvpIoPTNVkONSmaWOwmsDagJu6o

{
       "language": "uz",
       "type": "project",
       "image": "images.webp",
       "title": "Learning Golang",
       "body": "Golang is a statically typed programming language developed by Google...",
       "meta_tag": "golang,programming,backend"
}