DELETE http://localhost:8080/delete/9
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6InNob2toMUBleGFtcGxlLmNvbSIsImV4cCI6MTc2MDM2ODY1NywidXNlcm5hbWUiOiJzaG9raDEifQ.V_m980fZgVsF15HdOzNc6HW3QBCtT2EzBlXIVQugW6k